/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasM2;

import javax.swing.table.DefaultTableModel;
import prj.proy_cs.cls_funcionesM2;

/**
 *
 * @author Derek
 */
public class JF_mostrarRutinas extends javax.swing.JFrame {

        /**
         * Creates new form JF_mostrarRutinas
         */
        public JF_mostrarRutinas() {
                initComponents();
                llenartbl();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                btn_aceptar = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                txta_lista = new javax.swing.JTextArea();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setLocation(new java.awt.Point(600, 170));
                setUndecorated(true);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setBackground(new java.awt.Color(204, 204, 204));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                btn_aceptar.setText("ACEPTAR");
                btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_aceptarActionPerformed(evt);
                        }
                });
                jPanel1.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

                txta_lista.setEditable(false);
                txta_lista.setColumns(20);
                txta_lista.setRows(5);
                jScrollPane2.setViewportView(txta_lista);

                jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 710, 320));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 430));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
                // TODO add your handling code here:
                dispose();
        }//GEN-LAST:event_btn_aceptarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(JF_mostrarRutinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(JF_mostrarRutinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(JF_mostrarRutinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(JF_mostrarRutinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new JF_mostrarRutinas().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_aceptar;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea txta_lista;
        // End of variables declaration//GEN-END:variables

        private void llenartbl() {
              txta_lista.setText("\tRUTINA"+"\tDEPORTE"+"\tDESCRIPCION"+"\tDURACION"+"\n"+new cls_funcionesM2().mostrarRutina());
              
        }
}
