/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasM2;

import prj.proy_cs.JF_menu;

/**
 *
 * @author Derek
 */
public class JF_menuCatalogo extends javax.swing.JFrame {

    /**
     * Creates new form JF_menuCatalogo
     */
    public JF_menuCatalogo() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jbl_resgistroUsu3 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                ico_catDeportes = new javax.swing.JLabel();
                jbl_catDeportes = new javax.swing.JLabel();
                ico_retrocerder = new javax.swing.JLabel();
                ico_catUsuarios = new javax.swing.JLabel();
                jbl_Catusuarios1 = new javax.swing.JLabel();
                ico_catRutinas = new javax.swing.JLabel();
                jbl_rutinas = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jbl_Catusuarios2 = new javax.swing.JLabel();

                jbl_resgistroUsu3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
                jbl_resgistroUsu3.setForeground(new java.awt.Color(255, 255, 255));
                jbl_resgistroUsu3.setText("DESACTIVAR USUARIOS");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setLocation(new java.awt.Point(600, 170));
                setUndecorated(true);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setBackground(new java.awt.Color(51, 51, 51));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                ico_catDeportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_deportes128.png"))); // NOI18N
                ico_catDeportes.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ico_catDeportesMouseClicked(evt);
                        }
                });
                jPanel1.add(ico_catDeportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

                jbl_catDeportes.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
                jbl_catDeportes.setForeground(new java.awt.Color(255, 255, 255));
                jbl_catDeportes.setText("DEPORTES");
                jPanel1.add(jbl_catDeportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

                ico_retrocerder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_retroceder.png"))); // NOI18N
                ico_retrocerder.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ico_retrocerderMouseClicked(evt);
                        }
                });
                jPanel1.add(ico_retrocerder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                ico_catUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_usuarios128.png"))); // NOI18N
                ico_catUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ico_catUsuariosMouseClicked(evt);
                        }
                });
                jPanel1.add(ico_catUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

                jbl_Catusuarios1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
                jbl_Catusuarios1.setForeground(new java.awt.Color(255, 255, 255));
                jbl_Catusuarios1.setText("CATALOGOS");
                jPanel1.add(jbl_Catusuarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

                ico_catRutinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_rutinas128.png"))); // NOI18N
                ico_catRutinas.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ico_catRutinasMouseClicked(evt);
                        }
                });
                jPanel1.add(ico_catRutinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

                jbl_rutinas.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
                jbl_rutinas.setForeground(new java.awt.Color(255, 255, 255));
                jbl_rutinas.setText("RUTINAS");
                jPanel1.add(jbl_rutinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

                jSeparator1.setBackground(new java.awt.Color(255, 255, 51));
                jSeparator1.setForeground(new java.awt.Color(255, 255, 51));
                jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 270, 20));

                jbl_Catusuarios2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
                jbl_Catusuarios2.setForeground(new java.awt.Color(255, 255, 255));
                jbl_Catusuarios2.setText("USUARIOS");
                jPanel1.add(jbl_Catusuarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 460));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void ico_retrocerderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_retrocerderMouseClicked
        // TODO add your handling code here:
        //COMENTADO PARA PROBRAR   -->   //dispose();
        JF_menu JFM = new JF_menu();
        JFM.setVisible(true);
    }//GEN-LAST:event_ico_retrocerderMouseClicked

    private void ico_catUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_catUsuariosMouseClicked
        // TODO add your handling code here:
        dispose();
        JF_menuUsuarios_m2 JF =new JF_menuUsuarios_m2();
        JF.setVisible(true);
    }//GEN-LAST:event_ico_catUsuariosMouseClicked

    private void ico_catDeportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_catDeportesMouseClicked
        dispose();
        JF_menuDeportes JF= new JF_menuDeportes();
        JF.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_ico_catDeportesMouseClicked

        private void ico_catRutinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_catRutinasMouseClicked
                // TODO add your handling code here:
                dispose();
                new JF_menuRutinas().setVisible(true);
        }//GEN-LAST:event_ico_catRutinasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_menuCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_menuCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_menuCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_menuCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_menuCatalogo().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel ico_catDeportes;
        private javax.swing.JLabel ico_catRutinas;
        private javax.swing.JLabel ico_catUsuarios;
        private javax.swing.JLabel ico_retrocerder;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JLabel jbl_Catusuarios1;
        private javax.swing.JLabel jbl_Catusuarios2;
        private javax.swing.JLabel jbl_catDeportes;
        private javax.swing.JLabel jbl_resgistroUsu3;
        private javax.swing.JLabel jbl_rutinas;
        // End of variables declaration//GEN-END:variables
}
